version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Entered the install phase...
      - aws cloudformation package --template-file template.yaml --s3-bucket all-lambda-code-deploy-bucket --output-template-file outputTemplate.yaml

artifacts:
  type: zip
  files:
    - template.yaml
    - outputTemplate.yaml